build:
  stage: build
  image: ${BUILD_IMAGE}
  before_script:
    - cmake --version
    #- /jfrog rt config MyArtifactory --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_PASS
  script:
    - echo "building..."
    - cmake -H. -BDebug -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=YES
    - mkdir build && cd build
    - cmake ..
    - make
    - cd ../scripts
    - ./package.sh
    - tar -cvzf ${TEST_ARTIFACT} ../build/test
    - mv ${BUILD_ARTIFACT} ${CI_PROJECT_DIR}
    - mv ${TEST_ARTIFACT} ${CI_PROJECT_DIR}
    - ls -a ../build/test
  artifacts:
    paths:
      - ${BUILD_ARTIFACT}
      - ${TEST_ARTIFACT}
  # rules:
  # - if: $CI_MERGE_REQUEST_IID
  # - if: $CI_COMMIT_TAG
  # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
