/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atakmap_android_plugintemplate_HelloJni */

#ifndef _Included_com_atakmap_android_plugintemplate_HelloJni
#define _Included_com_atakmap_android_plugintemplate_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_atakmap_android_plugintemplate_HelloJni
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atakmap_android_plugintemplate_HelloJni_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
